import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "@/app/globals.css";
import "remixicon/fonts/remixicon.css";
import NextSessionProvider from "@/context/SessionProvider";
import { revalidatePath } from "next/cache";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NextSessionProvider>
          <main>{children}</main>
        </NextSessionProvider>
      </body>
    </html>
  );
}
